Create table meal_details (mtid Serial Primary Key, mtname varchar(50), mtimage varchar(40), mtbody VARCHAR, mtcost INTEGER, mttxtcost VARCHAR(10),mtlinkname VARCHAR(25), homepage Boolean, pickyeater boolean);

INSERT INTO meal_details
    (mtname, mtimage, mtbody, mtcost, mttxtcost, mtlinkname, homepage, pickyeater)
VALUES
('Nibble','../../images/nibble.jpg','This brief series empowers parents to know which foods to focus on to help their children be the healthiest they can be and how to go about doing just that. You will learn what the science is saying about organic foods, which small daily changes will add up quickly to good health and ideas for meals to create each week for breakfast, lunch and dinner.', 10,'$10','Nibble',true,true),
('Snack', '../../images/snack.jpg', 'In this introductory series you will learn about epigenetics: the study of how our genetic history affects our health. You will also learn why knowing what exactly to eat can be so confusing, which doctors are expert research scientists on food and nutrition and which foods we should be eating for optimal health. You will then learn about your microbiome, which foods injure your body and which foods protect it so you can make informed decisions about how to feed yourself and your family.', 25, '$25','Snack', true,true),
('Dine','../../images/dine.jpg','The dine series is designed to give you more in-depth information about WHY plant-based eating is so effective at       creating health. In this series you will learn about calorie density, food synergy, how governmental policies affect food choices, how to be informed about medication you may need to take,how cheese, dairy, meat and artificial sweeteners affect our health and better substitutes for better health.',25,'$25','dine',true,true),
('Feast', '../../images/Feast.jpg', 'This 4 week program was created for busy people who are ready to give plant-based eating a try so they can get rid of chronic disease, balance their hormones, lose weight and feel great! The series includes four weeks of informational videos that accompany four weeks of meal-prep recipes and how-to videos, so you can cook on one day and eat for a week! This is how I currently follow my WFPB routine as the only plant-based eater in my home, and how I juggle cooking for myself and my family. All the recipes are easy to make and easy to customize to your tastes and preferences. Ready to eat your way to a healthier you?', 75, '$75','Feast',true,true),
('All Access',  '../../images/aaccess.png', 'Are you starving for the science on plant based eating, but short on the time needed to read through every book and watch every link on my free resources page? Become an ALL ACCESS member and gain access to every video, ‘dig deeper’ section and recipe on this website. You have access to everything here FOREVER! All Access membership include all the series’ on the main page, the ‘picky eaters’ page, and my recipe videos and printable recipes too! You can have access to it all for $165--$40 less than it will cost to purchase everything separately!', 165,'$165','allaccess',true, true),
('Picky Eaters', '../../images/pickyeater.jpg', 'On the Picky Eaters page you’ll find specific information tailored to individuals: from expecting mothers and families to athletes; those interested in how plant based eating helps the environment; to those hoping to prevent or reverse heart disease or autoimmune and hormonal disorders. I also have a series specific to men, women and those over 50. These videos are best enjoyed by those who already have a basic understanding of plant based nutrition and want specific information catered to their individual needs. I’ve also included a ‘dig deeper’ section with each video containing links to additional information about the science or to specific products I highlight in the videos. If you’re interested in how to tailor plant based nutrition to your personal needs--this page is for you!', 0, 'Various','pickyeaters',true, false),
('Immune',  '../../images/immune2.jpg','In this brief series I will review the foods and habits that help to strengthen our immune system and keep us healthy and balanced--even during times of crisis. I will also go over foods and habits that do us harm, throw our bodies out of balance and open the doors to illness and chronic disease. Our daily choices and actions can protect us and heal us! Here’s to your good health!', 0, 'Free', 'Immune',true, false),
('Autoimmune','' ,'Learn about how what you eat affects autoimmune disorders and how changing your eating habits can have a huge impact on how you feel.', 5,'$5', 'Autoimmune', false, true),
('Environment','' ,'This series is an overview of what the climate research experts are saying about how our current lifestyle is impacting our environment and changes big and small we can make now to protect future generations.', 10,'$10','Environment',false, true),
('Food Focus','',' Find out which foods to focus on depending on your specific needs, from athletes to cardiovascular health--certain foods can help us heal and perform at our best.', 5, '$5','Foodfocus',false, true),
('For your Family','','This video gives a deeper look into what researchers are saying about healthy habits to foster in our homes that will protect children and adults alike. Covering sleep, shift work, skin and the importance of hormonal balance.', 10, '$10','foryourfamily',false, true),
('Pregnancy and children','', 'Is eating a WFPB diet safe for pregnant women and small children? In this video you’ll learn the details about what the research is showing about how to have a healthy pregnancy and how to raise healthy kids!', 5,'$5', 'Pregnancy', false, true),
('50+','', 'This video gives personal guidance on a range of health topics facing those over the age of 50. Learn more about how following a WFPB lifestyle can help you avoid chronic conditions as you age.',10, '$10','50+', false, true),
('Men','', 'In this video, I cover a range of health issues specific to men and what the research is saying about how eating a WFPB diet can help you avoid chronic conditions and perform at your best.',10, '$10', 'Men', false, true),
('Women','', 'As women, it is so important we make our health a priority so we can manage our vast and varied responsibilities. This video reviews the whys and hows of doing just that!',10, '$10', 'women', false, true),
('Meal prep recipes/videos and favorite links','', 'Includes 16 videos and dozens of recipes as well as links to additional recipes',40,'$40','Recipe', false, true);
('The Lonely Vegan','', 'I created this video to help those of you who are the only plant-based eaters in your home or circle of friends/family.  I am too!  This free video gives you tips about how to foster healthy relationships while changing your eating habits.',0,'Free','Vegan', true, false);